apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiodata3pvc
  namespace: ddannerdemo
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 55Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fioconf3pvc
  namespace: ddannerdemo
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddfio3deployment
  namespace: ddannerdemo
spec:
  selector:
    matchLabels:
      app: ddfio3
  replicas: 1
  template:
    metadata:
      labels:
        app: ddfio3
    spec:
      containers:
        - name: ddfio3
          labels:
            app: ddfio3
          image: docker.io/ddanner123/ddfio
          ports:
            - containerPort: 2222
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "echo --- NEW START $(hostname) --- >> /fiodata/datastream.out ; /usr/sbin/sshd ; cp -r /bin/runfio.sh /fioconf/runfio.sh ; /fioconf/runfio.sh " ]
          volumeMounts:
            - name: fiodata3
              mountPath: "/fiodata"
            - name: fioconf3
              mountPath: "/fioconf"
      nodeName: "compute-2.escc.frankfurt.de.ibm.com"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: scale.spectrum.ibm.com/role
                operator: In
                values:
                - storage
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ddfio3
            topologyKey: kubernetes.io/hostname
      volumes:
        - name: fiodata3
          persistentVolumeClaim:
            claimName: fiodata3pvc
        - name: fioconf3
          persistentVolumeClaim:
            claimName: fioconf3pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ddfio3service
  namespace: ddannerdemo
spec:
  selector:
    app: ddfio3
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
