apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiodata2pvc
  namespace: ddannerdemo
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 55Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fioconf2pvc
  namespace: ddannerdemo
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddfio2deployment
  namespace: ddannerdemo
spec:
  selector:
    matchLabels:
      app: ddfio2
  replicas: 1
  template:
    metadata:
      labels:
        app: ddfio2
    spec:
      containers:
        - name: ddfio2
          labels:
            app: ddfio2
          image: docker.io/ddanner123/ddfio
          ports:
            - containerPort: 2222
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "echo --- NEW START $(hostname) --- >> /fiodata/datastream.out ; /usr/sbin/sshd ; cp -r /bin/runfio.sh /fioconf/runfio.sh ; /fioconf/runfio.sh " ]
          volumeMounts:
            - name: fiodata2
              mountPath: "/fiodata"
            - name: fioconf2
              mountPath: "/fioconf"
      nodeName: compute-1.escc.frankfurt.de.ibm.com
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: scale.spectrum.ibm.com/role
                operator: In
                values:
                - storage
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ddfio2
            topologyKey: kubernetes.io/hostname
      volumes:
        - name: fiodata2
          persistentVolumeClaim:
            claimName: fiodata2pvc
        - name: fioconf2
          persistentVolumeClaim:
            claimName: fioconf2pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ddfio2service
  namespace: ddannerdemo
spec:
  selector:
    app: ddfio2
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
